### ISSUE TITLE
[BUG] Inconsistent CTD when entering Whiterun main city worldspace

### ISSUE THREAD

**Issue by Vacant-Eyes** [DaymareOn/hdtSMP64#100]
**Describe the bug**
Inconsistent CTD (seems to be about 50% of the time) when entering Whiterun city main worldspace. Only occurs with FSMP enabled. Alan's Crashlogger references FSMP in the probable call stack section of the log, hence the report here.

**To Reproduce**
1. Enter Whiterun city worldspace through the gate, or an interior building.

**Expected behavior**
2. May CTD around the point that loading concludes (but still on loading screen).

**Screenshots and videos**
Not applicable.

**Desktop:**
 - OS: Windows 10
 
**FSMP**
- Installed version: 1.50.7-rc1, latest
- CUDA: Non-Cuda install
- AVX: AVX (tested with intel's CPU diagnostic tool. Result for AVX test: "..AVX is supported by this CPU..")

**SKSE**
- installed version: 2.2.3

**Skyrim**
- Installed version number: 1.6.640, latest Steam version

**Required files**

(using default, unaltered configs.xml)

Here's the crash-2023-04-18-21-00-20.log, and hdtSMP64.log: 

[crash-2023-04-18-21-00-20.log](https://github.com/DaymareOn/hdtSMP64/files/11266702/crash-2023-04-18-21-00-20.log)
[hdtSMP64.log](https://github.com/DaymareOn/hdtSMP64/files/11266703/hdtSMP64.log)

xml file format isn't supported by github, so here's an alternate link if needed containing the configs.xml: https://mega.nz/folder/fz4hkZZK#wd5AQ7TiOM6nCuYOKvpGfQ

**Additional context**
I'm running FSMP alongside CBPC. FSMP is not flagged for any file conflicts in MO2.

Hopefully this is helpful, cheers.

**Comment by alandtse** [comment]
This crashlog does not point to hdtsmp as being related. The line
```
	[13] 0x7FFA43B1A999       hdtSMP64.dll+00BA999	cmp byte ptr [rbx+0x10], 0x00 |  C:\Games\Faster HDT-SMP\skse64_2_02_02\src\skse64\hdtSMP64\Hooks.cpp:306 ?onFrame@UnkEngine@hdt@@QEAAXXZ
```
is too low in the call stack to be relevant. Basically hdt runs every frame and you're seeing a note that hdt was called.

You're crashing in skse64.dll and the callstack is noting some issues with the save. Report to skse. Only then can debug this.
```
Unhandled exception "EXCEPTION_ACCESS_VIOLATION" at 0x7FFA7660D466 skse64_1_6_640.dll+005D466	mov r15, [rax+0x18]
```
