### ISSUE TITLE
[BUG] Random CTD 

### ISSUE THREAD

**Issue by DragonBlade117** [DaymareOn/hdtSMP64#109]
**Describe the bug**
I consistantly get CTDs on new saves and existing saves.

**To Reproduce**
There doesn't seem to be a rhyme or reason to it, but it seems to prolong it when I change areas, but it happens anywhere.

**Expected behavior**
No crashes

**Desktop (please complete the following information):**
 - OS: [Win11 Pro]

** FSMP**
- Tried 1.50.9rc1
- CUDA:  Both No_CUDA or CUDA
- AVX: No_AVX and AVX. 
**SKSE**
- 2.0.20

**Skyrim**
-  1.5.97

[crash-2023-08-23-01-43-29.log](https://github.com/DaymareOn/hdtSMP64/files/12414359/crash-2023-08-23-01-43-29.log)
[crash-2023-08-23-01-15-00.log](https://github.com/DaymareOn/hdtSMP64/files/12414360/crash-2023-08-23-01-15-00.log)
[crash-2023-08-23-01-04-37.log](https://github.com/DaymareOn/hdtSMP64/files/12414361/crash-2023-08-23-01-04-37.log)
[hdtSMP64.log](https://github.com/DaymareOn/hdtSMP64/files/12414364/hdtSMP64.log)
[Skyrim.zip](https://github.com/DaymareOn/hdtSMP64/files/12414373/Skyrim.zip)

**Comment by DaymareOn** [comment]
2nd and 3rd crashes aren't related to FSMP, see FSMPU.
1st crash happens on the parallelization code. I would bet a crash happened elsewhere in the parallelized threads and it caused this crash.
