### ISSUE TITLE
[BUG] Causing saves to freeze before it tries to load

### ISSUE THREAD

**Issue by PrinceJaxonHellsing** [DaymareOn/hdtSMP64#110]
I feel like an idiot for asking help for this on nexus and I never bothered to read where bug reports are, anyway here's my issue. I don't know what caused this but Faster HDT-SMP was working fine, I didn't download more mods when I was using it while playing skyrim. All of the sudden my game freezes during combat and crashes, and for a few weeks I didn't know what mod was causing this, until recently I found out it was Faster HDT-SMP. So when Faster HDT-SMP is enabled now and I try to load a quick save, a save, and an auto save my game freezes and stops responding when loading it. Since it freezes and stops responding it won't crash to desktop so I have to close it with task manager, which of course means the game doesn't generate crash logs when this happens.

Desktop: windows 10

Faster HDT-SMP: seems to be any version as I've tried 2.0.2-beta1, and 1.50.9-rc1

SKSE Version: 6.6.640

I don't think I have Cuda or AVX, and I've never chosen any options with them

**Comment by DaymareOn** [comment]
Hmm, I have no way to debug this.
If it was on my machine, I would try to reproduce this while debugging, and see where it hangs.
But this requires to set up a dev environment. If you got the courage and the time, you can see my [article ](https://www.nexusmods.com/skyrimspecialedition/articles/3606) about this. 

But an advice: quick saving breaks saves.
An easy way to avoid this is to use the option
RegularQuicksaves = true                # Makes quick saves into regular saves
in the Engine Fixes mod.
