### ISSUE TITLE
Crashes to Desktop when putting on clothes/armors and entering water. 

### ISSUE THREAD

**Issue by Alt-Ctrl-Crash** [DaymareOn/hdtSMP64#112]
**Describe the bug**
When attempting to put on custom armors/clothes such as Dimitrescu CBBE 3BA SE the game crashes to my desktop.
The game crashes when entering water.

**To Reproduce**
1. Go to inventory put on Dimitrescu CBBE 3BA SE(or Something  Similar) or enter a body of water.

**Expected behavior**

The game will crash.

**Screenshots and videos**
If applicable, add screenshots or videos to help explain your problem.

N/A

**Desktop (please complete the following information):**
 - OS Windows 11.

** FSMP**
- 2.0.4-beta 1
- No_CUDA
- No_AVX,
- 
**SKSE**
- installed version:
 2.2.3

**Skyrim**
- Installed version number
Game version 1.6.640

**Required files**
[configs.xml.txt](https://github.com/DaymareOn/hdtSMP64/files/13401929/configs.xmlCOPY.txt)

[hdtSMP64.log]
(https://github.com/DaymareOn/hdtSMP64/files/13401902/hdtSMP64.log)

**Additional context**
Regarding the CTD that occurs when player enters water, I have only tested the bug in the areas in and around Riften.

I tried using 1.50.9-rc1 and 1.50.7-rc1 but I encountered the same bugs.  The bug occurs on versions 2.0.4-beta 1, 1.50.9-rc1, and 1.50.7-rc1.

I have attached additional logs below.
Crash Log.txt:
[crash-2023-11-18-22-20-26.log](https://github.com/DaymareOn/hdtSMP64/files/13401946/crash-2023-11-18-22-20-26.log)
Crash Log Report.txt:
[crash-2023-11-18-22-20-26-REPORT.txt](https://github.com/DaymareOn/hdtSMP64/files/13401948/crash-2023-11-18-22-20-26-REPORT.txt)

**Comment by DaymareOn** [comment]
Not related to FSMP.
See FSMPU

**Comment by DaymareOn** [comment]
Not related to FSMP.
See FSMPU
