### ISSUE TITLE
[BUG] ... CTD happens when ... I zone

### ISSUE THREAD

**Issue by Jimanimbo** [DaymareOn/hdtSMP64#113]
**Describe the bug**

**To Reproduce**
9/10 zone changes crashes to desktop.  Game is autosaved successfully in new zone.  I have to load  game from the autosave.

**Expected behavior**
I expect lag while the 5 followers zone through, but not crash.

**Screenshots and videos**
If applicable, add screenshots or videos to help explain your problem.
None

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Wine]
Windows 11

** FSMP**
- Installed version 2.04 Beta (peviously 1.49.0).
-  AVX512?

**SKSE**
- installed version 2.2.3
(You can check it in the bottom left part of the screen, when looking at your MCMs.)

**Skyrim**
- Installed version number 1.6.64.08
(You can check it in the bottom left part of the screen, when looking at your MCMs.)

**Required files**
- Join your configs.xml 
[crash-2023-11-28-21-15-18.log](https://github.com/DaymareOn/hdtSMP64/files/13493406/crash-2023-11-28-21-15-18.log)

- Join your hdtSMP64.log 
-  [hdtSMP64.log](https://github.com/DaymareOn/hdtSMP64/files/13493397/hdtSMP64.log)
-

**Additional context**

**Comment by DaymareOn** [comment]
Not related to FSMP

**Comment by Jimanimbo** [comment]
Thank you so much!
