### ISSUE TITLE
Unable to select version in installer...

### ISSUE THREAD

**Issue by Nia-rrobyn** [DaymareOn/hdtSMP64#115]
**Describe the bug**
Installer bug

**To Reproduce**
1. Go to MO2 and install the mod as usual using the downloaded file...
2. Click on install and allow the window to pop up for the FOMOD installer
3. Notice the faded version selection section...
4. See the GOG version selected and notice that you cannot change it even though the download was not GOG tagged. 

**Expected behavior**
I would personally as an old school modder allow the version to be selected and release simply one version of the installer has all the possible necessary options for users.  I get making one for each version because many people do not tend to know what version of the game they are actually playing.  I had my game will not function correctly now unless I want to overhaul my mod list and remove some things due to version update. 

**Desktop (please complete the following information):**
 - OS: Windows 10

** FSMP**
- I uninstalled the old files to update so my game stops barking at me and ran into the issue with the installer. I run the steam version of Skyrim AE (Skyrim SE that came with AE DLC)
- CUDA: No_CUDA
- AVX: No_AVX

**SKSE**
- 2.2.4

**Skyrim**
- 1.6.1

**Required files**
- Join your configs.xml
- Join your hdtSMP64.log

**Comment by snottyone** [comment]
you are trying to install the current version of FSMP on the incompatible game version 1.6.1130
wait for an update, which will be published shortly.

**Comment by CMT493** [comment]
This is still a problem with MO2. All supported game version options are NOT selectable in the FOMOD.
The other options AVX etc. can be selected, so basically the mod cannot be installed. This has been the case for a long time with the latest version 2.5.1, and 2.5.0, 2.4.0 and others. The last version where the FOMOD works in my experience is 1.50.9-rc1.
I have tried to open this issue as a "New Issue" but the system is not opening any text box for me to report it, so I am commenting here. Thank you.

**Comment by snottyone** [comment]
> NOT selectable in the FOMOD. 

correct.
because your installed game version is detected and chosen automatically.
this is hard to see in <s>dumb</s> dark modes, but visible even them when you look closely,
GOG and Steam versions are correctly detected.

all errors in detection are down to non-standard installs (a second copy in a NOLVUS folder e.g., see below, registry entry) and/or cracked versions of the game (lack of registry entry).
problems will also arise with such installs when using LOOT or FNIS.

if you have several legitimate game version installed, just fish your desired version's dll out of the zip file (changing the bethesda skyrim registry entry to match the path of your game may work)

**Comment by shepoil** [comment]
Since I landed here looking for the same problem. If it can be useful to anyone, I would like to add that **using the "_FOMOD Plus_" plugin for MO2 prevents the FSMP fomod from auto-selecting the right version**. Disabling FOMOD Plus solved my issue.

**Comment by snottyone** [comment]
> Since I landed here looking for the same problem. If it can be useful to anyone, I would like to add that **using the "_FOMOD Plus_" plugin for MO2 prevents the FSMP fomod from auto-selecting the right version**. Disabling FOMOD Plus solved my issue.

thank you very much for that observation, FOMOD plus knows it has a problem
