### ISSUE TITLE
Not COmpatible with the new 6130 update of ae

### ISSUE THREAD

**Issue by Daywalkerhawk** [DaymareOn/hdtSMP64#116]
Mo says the dll is outdated and will be disabled, i also cant change the game version in the fmod installer on Nexus it allways selects gog version

**Comment by snottyone** [comment]
there is a beta version for 1130 on the [FSMP discord ](https://discord.gg/raDz3UZ8)
the installer doesn't know about 1130 yet, so will install GOG, which is overwritten by the beta dll

**Comment by Daywalkerhawk** [comment]
ah nice ill get it instand, and its working one problem solved so far just waiting for fuz do roh now :)

**Comment by DaymareOn** [comment]
1.6.1130 isn't supported anymore.
