### ISSUE TITLE
[BUG] Fatal error when launching the game (version 1.6.1130.0)

### ISSUE THREAD

**Issue by jaylenxnicci** [DaymareOn/hdtSMP64#117]
Hello,

I have the latest update of Skyrim Anniversary Edition, which is version 1.6.1130.0. I also have the latest version of SKSE, which is version 2.2.5. 

I downloaded the latest version of your Faster HDT-SMP 2.1.0 and I encounter an error when I want to start my game. SKSE Plugin Loader tells me this: "hdtSMP64dll: disabled, fatal error occured while loading plugin". 

Thank you for your work.

**Comment by snottyone** [comment]
hey

this vortex-related bug is being worked on.
you can track progress in [this thread](https://discord.com/channels/939147296963166338/1183490096775839855) in the [FSMP Discord](https://discord.gg/UMSWUTTD)

**Comment by jaylenxnicci** [comment]
Thank you :)

**Comment by Seed8193** [comment]
You can also read this thread. It's a compilation of all SKSE plugins : https://modding.wiki/en/skyrim/users/skse-plugins
