### ISSUE TITLE
[BUG] AVX 512 Non Cuda v1.6.640 is the wrong .dll

### ISSUE THREAD

**Issue by Alphonze17** [DaymareOn/hdtSMP64#122]
The .dll present in this file option is incorrect, causes wrong version error on launch.

**Comment by snottyone** [comment]
no, it doesn't. correct avx512 dll for FSMP 2.1.3.
check your game version.

**Comment by Alphonze17** [comment]
I even tried to manually put that dll in, same error. Putting in the avx2 for 1.6.640 works though. Triple checked.

**Comment by DaymareOn** [comment]
From the next fomod:

NOT SUPPORTED ON INTEL CPU!!!
Do NOT come with a bug report concerning AVX512 if this bug doesn't happen with the AVX2 build, except if you come with the solution too.

"Intel does not officially support AVX-512 family of instructions on the Alder Lake microprocessors.
Intel has disabled in silicon (fused off) AVX-512 on recent steppings of Alder Lake microprocessors to prevent customers from enabling AVX-512.
In older Alder Lake family CPUs with some legacy combinations of BIOS and microcode revisions, it was possible to execute AVX-512 family instructions
when disabling all the efficiency cores which do not contain the silicon for AVX-512."

Thanks for this report, though :)

**Comment by Alphonze17** [comment]
I don't follow? 

I have an AMD 7800x3d and never mentioned anything to do with CPU feature compatibility.

My issue was only concerning the particular .dll inside the AVX512 for 1.6.640 - I just used one from a different folder which also matched my current version at the time. I only reported it because the .dll in the folder I specified, was not correct for the version it stated it was for. 

Pretty sure this is not an issue in the later versions anyway, as I updated and didn't get the same error this time.

**Comment by DaymareOn** [comment]
Sorry, most reports about AVX512 are about Intel cpus and I assumed wrongly.
Will relook at this.

**Comment by snottyone** [comment]
can't confirm this.
FSMP 2.1.1 AVX512 no cuda with 1.6.640 launches without problems on an R9 7950X3D

**Comment by DaymareOn** [comment]
I have checked the fomod logic, and the visual studio build logic, and haven't found anything.
Your processor should be compatible with AVX512, so it isn't this either.

So, it seems you're right :) :
"Pretty sure this is not an issue in the later versions anyway, as I updated and didn't get the same error this time."
