### ISSUE TITLE
hdtSMP64.dll: disabled, incompatible with current version of the game. Skyrim AE version  1.6.1170

### ISSUE THREAD

**Issue by PabloGun** [DaymareOn/hdtSMP64#124]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots and videos**
If applicable, add screenshots or videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Wine]

** FSMP**
- Installed version
- CUDA: No_CUDA or CUDA?
- AVX: No_AVX, AVX, AVX2, AVX512?

**SKSE**
- installed version
(You can check it in the bottom left part of the screen, when looking at your MCMs.)

**Skyrim**
- Installed version number
(You can check it in the bottom left part of the screen, when looking at your MCMs.)

**Required files**
- Join your configs.xml
- Join your hdtSMP64.log

**Additional context**

**Comment by dutchblizzard** [comment]
the skse plugin need update so its compatible with the newest skyrim version. and i'm waiting on that. so far its the last one for me

**Comment by DaymareOn** [comment]
It should be solved with FSMP > 2.3.1.
