### ISSUE TITLE
[BUG] ... happens when ... 

### ISSUE THREAD

**Issue by fodamaster** [DaymareOn/hdtSMP64#128]
**Describe the bug**
Dear all, I'm having constant CTDs when loading saves. In crash logger I always observe the following information in probable call stack that has caught my attention:

**"hdtSMP64.dll+00BB939 cmp byte ptr [rbx+0x10], 0x00 | C:\Games\Faster HDT-SMP\skse64_2_02_05\src\skse64\hdtSMP64\Hooks.cpp:314 ?onFrame@UnkEngine@hdt@@QEAAXXZ" .**

To reiterate: CTDs only occur when loading saves. During the game running, they do not occur.
I'm testing it in Windhelm. I start a new game and everything works perfectly. Saved. When loading, CTD happens and has always the same probable call stack.
If you can help me with any clues I would be grateful.
Skyrim version: 1.6.1130
SKSE: 2.2.5
FSMP: 2.1.3

**To Reproduce**
CTDs only occur when loading saves. During the game running, they do not occur.
I'm testing it in Windhelm. I start a new game and everything works perfectly. Saved. When loading, CTD happens and has always the same probable call stack.

**Desktop (please complete the following information):**
 - OS: Windows 10

** FSMP**
- Installed version:  2.1.3
- CUDA: No_CUDA
- AVX: Tested with No_AVX, AVX and AVX2. Actually, AVX2.

**SKSE**
- installed version: 2.2.5

**Skyrim**
- Installed version number: 1.6.1130

**Required files**
[configs.txt](https://github.com/DaymareOn/hdtSMP64/files/14184665/configs.txt)
[crash-2024-02-06-17-38-23.log](https://github.com/DaymareOn/hdtSMP64/files/14184671/crash-2024-02-06-17-38-23.log)
[skse64.log](https://github.com/DaymareOn/hdtSMP64/files/14184673/skse64.log)
[crash-2024-02-06-17-38-23-REPORT.txt](https://github.com/DaymareOn/hdtSMP64/files/14184677/crash-2024-02-06-17-38-23-REPORT.txt)
[hdtSMP64.log](https://github.com/DaymareOn/hdtSMP64/files/14184678/hdtSMP64.log)

**Comment by snottyone** [comment]
NOT an FSMP crash
if it's not the first line in the call stack, it's not connected
FSMP runs every frame, and is bound to appear in nearly every crash log

you crash is most likely engine fixes (which for 1130 needs achievements disabled at the very least)

**Comment by DaymareOn** [comment]
Not related to FSMP.
