### ISSUE TITLE
[BUG] Randomly Crashing, no apparent cause

### ISSUE THREAD

**Issue by SirLays** [DaymareOn/hdtSMP64#129]
**Describe the bug**
I would be doing normal actions within Skyrim (Walking around Whiterun, entering buildings, just standing still) and game would freeze for 1-2 seconds, before Crashing to the Desktop.

**To Reproduce**
1. Do normal Actions,
2. Crash

**Expected behaviour**
Not Crashing.

**Screenshots and videos**
Nothing to give, unfortunately. 

**Desktop (please complete the following information):**
 - OS: Windows 10

** FSMP**
- Installed version: 2.2.1 (Nexus Latest)
- CUDA: No_CUDA
- AVX: No_AVX,

**SKSE**
- installed version
2.2.6 rel

**Skyrim**
- Installed version number
1.6.1170.0.8

**Required files**
- Join your configs.xml 
[config.txt](https://github.com/DaymareOn/hdtSMP64/files/14236997/config.txt)

- Join your hdtSMP64.log
[hdtsmp64Log.txt](https://github.com/DaymareOn/hdtSMP64/files/14237016/hdtsmp64Log.txt)

- Skyrim Trainwreck Log
[2024-02-11-19-14-21.log](https://github.com/DaymareOn/hdtSMP64/files/14236972/2024-02-11-19-14-21.log)

**Additional context**
Load Order
[loadorder.txt](https://github.com/DaymareOn/hdtSMP64/files/14237056/loadorder.txt)

Mod List
[modlist.txt](https://github.com/DaymareOn/hdtSMP64/files/14237062/modlist.txt)

**Comment by DaymareOn** [comment]
Happens during concurrency management :/
Hard to know what provokes this (which 99% probability is it's provoked by something outside concurrency management).
