### ISSUE TITLE
hdtSMP64.dll: disabled, fatal error occurred while loading plugin

### ISSUE THREAD

**Issue by nt5raham** [DaymareOn/hdtSMP64#131]
**Describe the bug**
SKSE loader displays this error almost immediately after starting the game:

"hdtSMP64.dll: disabled, fatal error occurred while loading plugin"

**To Reproduce**
1. Start the game
2. See error

**Expected behavior**
Booting all the way to the main menu would be nice.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro

** FSMP**
- Installed version:  2.2.1
- CUDA: No_CUDA or CUDA?  Both the same result.
- AVX: No_AVX, AVX?  Both the same result.

**SKSE**
- installed version: 2.2.6

**Skyrim**
- Installed version number:  1170 Steam

**Required files**
- Join your configs.xml:  All default settings, no modifiers/variable changes.
- Join your hdtSMP64.log:  "hdtSMP64 200200"

**Additional context**
Out of 1,100 mods, this is the only .dll that will not load.   All mods/files mentioned on the mod page are up to date.

I have watched hdtSMP64.dll each time I changed the FOMOD trying to find a combination that worked (i.e. CUDA or No CUDA), and confirmed that the file is being changed in size, confirming that it is being provided by this mod.

**Comment by ChromeCreep** [comment]
Hey, if you're still struggling with this, turn off both No.ESP and MCM Menu for Faster HDT-SMP (FSMPM - The FSMP MCM). Should hopefully fix it.

**Comment by snottyone** [comment]
> Hey, if you're still struggling with this, turn off both No.ESP and MCM Menu for Faster HDT-SMP (FSMPM - The FSMP MCM). Should hopefully fix it.

no.esp ONLY WORKS ON 1.5.97
for all later version, the other provided esp is the one to use..
it's not the FSMP MCM malfunctioning, it's not installed correctly.

**Comment by DaymareOn** [comment]
Guys, I have made a test version to better debug these problems. Please dm me on discord (DaydreamingDay in the FSMP server, which invite is on the FSMP nexus description page). I need some tester to check that  it works before providing it on the nexus.
In the meantime, I close this bug. We'll reopen it if you, or somebody else suffering from a similar bug, comes back to me :)
