### ISSUE TITLE
[BUG] CTD when trying to start a new game

### ISSUE THREAD

**Issue by kinderdat** [DaymareOn/hdtSMP64#132]
**Describe the bug**
i try to start a new game, but it crashes after loading screen. game dosent crash when loading previous saves so idk what could be the issue, error is recent and no recent changes or downloaded mods. no prior crashing like this when making new games in the past too. 

**To Reproduce**
-

**Desktop (please complete the following information):**
 - OS: windows 11

** FSMP**
- tested on 2.0.3 beta , 2.1.3 , and latest 2.2.1
- CUDA: No_CUDA
- AVX: tested No_AVX,  AVX , and AVX2

**SKSE**
- 2.0.20

**Skyrim**
- 1.5.97

**Required files**
- Join your configs.xml
- Join your hdtSMP64.log

**Additional context**

**Comment by snottyone** [comment]
no crashlog, no hdtSMP64.log, no configs.xml

**Comment by kinderdat** [comment]
> no crashlog, no hdtSMP64.log, no configs.xml
my bad, new to using github. figuring out how to do things :_:

[Crash_2024_2_26_7-21-21.txt](https://github.com/DaymareOn/hdtSMP64/files/14410110/Crash_2024_2_26_7-21-21.txt)

[hdtSMP64.log](https://github.com/DaymareOn/hdtSMP64/files/14410126/hdtSMP64.log)

**Comment by snottyone** [comment]
your configs.xml has no values in it. that's why the game CTDs
you also have no-esp.dll loaded, which does not work in anything except 1.5.97
get the FSMP MCM esp instead, which may fix your problem.

**Comment by DaymareOn** [comment]
Not a FSMP bug.
