### ISSUE TITLE
[BUG] CTDs at random times

### ISSUE THREAD

**Issue by somestupidgirl** [DaymareOn/hdtSMP64#133]
With FSMP installed the game sometimes crashes when entering or exiting buildings and when loading saves, but also just at random moments, during combat, etc. It seems to be more frequent within interiors but all in all it seems very random which makes it difficult to replicate aside from trying to load saves or entering and exiting buildings until the game crashes. According to the CrashLogger log it seems that hdtSMP64.dll is the definitive culprit. I used to have Better Third Person Selection installed but uninstalling it has not made a whole lot of difference although it does result in less frequent CTDs in terms of being able to load saves. I still get such CTDs with only FSMP installed, just less frequently.

**Desktop:**
 - Windows 11

** FSMP**
- 2.2.1 (seems to happen regardless of what version I install however as I have tested previous versions as well)
- CUDA: No
- AVX: AVX512 (I have also tested the AVX and AVX2 builds but with the same results)

**SKSE**
- 2.02.03

**Skyrim**
- 1.6.640

**- Config XMLs:**
- Default XML files included on the FSMP Nexus download page, some overwritten by the files contained in the latest version of CBBE 3BA (3BBB)

**hdtSMP64.log:**

hdtSMP64 200102

**CrashLogger Log:**

https://pastebin.com/d4HQ50A8

**Comment by snottyone** [comment]
not an FSMP crash.
try disabling the save unbaker, you're crashing on autosave

**Comment by somestupidgirl** [comment]
Thank you, will try that.

**Comment by somestupidgirl** [comment]
No difference with Save Unbaker disabled.

Crash Log:

https://pastebin.com/jQACN8qV

**Comment by snottyone** [comment]
hmm, it's still an autosave crash.
did you start a new game with the unbaker disabled, or continue?
(also, if you haven't, set `RegularQuicksaves = true` in EngineFixes.toml)

**Comment by somestupidgirl** [comment]
Haven't started a new save to test it out but I just disabled autosave completely and no CTDs so far so it seems like you're correct in that it's an autosave issue. Thank you for the help. Now that the problem has been identified I'll be able to figure something out.

I still don't understand why the crash log lists hdtSMP64.dll when these autosave-related crashes happen though instead of the unbaker plugin for example.

**Comment by snottyone** [comment]
> I still don't understand why the crash log lists hdtSMP64.dll when these autosave-related crashes happen though instead of the unbaker plugin for example.

FSMP runs every frame, so it ends up in nearly every crashlog.
you'll know a real FSMP crash if you see a log - the whole stack section is ONLY fsmp then

**Comment by somestupidgirl** [comment]
Ah okay got it. Yeah that makes sense. Thanks again for the help. At least my game is significantly more stable now after disabling autosave. I've made too much progress in my current playthrough to start a new one to see if the overall problem persists but at least now I know it's something that's affecting the save/load process and not the physics plugin (which is actually a big relief since HDT SMP is always an essential part of my mod list).

**Comment by DaymareOn** [comment]
Not related to FSMP.
