### ISSUE TITLE
Periodically crashes to the desktop

### ISSUE THREAD

**Issue by Bonsan45030** [DaymareOn/hdtSMP64#136]
[2024-04-04-00-50-24.log](https://github.com/DaymareOn/hdtSMP64/files/14872799/2024-04-04-00-50-24.log)

https://pastebin.com/AtXt3unJ

**Comment by snottyone** [comment]
* it's not FSMP, which runs every frame and ends up in crash logs for that reason
* this crash is lighting/camera related (not a GREAT help, i know)

**Comment by DaymareOn** [comment]
Not related to FSMP.
