### ISSUE TITLE
[BUG] bone name case sensitive problem

### ISSUE THREAD

**Issue by s4e8** [DaymareOn/hdtSMP64#138]
FSMP bone name use the string cache, which is case insensitive, but bone name in xml is case sensitive. eg:
armor1 has a bone name "skirta1", armor2 has a bone name "SkirtA1". After load armor1, "skirta1" being cached.
If load armor2 later, bone "SkirtA1" become "skirta1", which don't match the name in HDT xml, produce bad physics behavior.

**Comment by DaymareOn** [comment]
We have no guarantee that the string cache will provide a lowercase or uppercase string.
So I guess the solution would be to systematically lowercase our inputs when looking.

**Comment by DaymareOn** [comment]
From what I understand, this is a skyrim bug we can't solve in FSMP.
These 2 bones' names will always collide in Skyrim.

The only solution is to not have collidable names.

**Comment by s4e8** [comment]
> From what I understand, this is a skyrim bug we can't solve in FSMP. These 2 bones' names will always collide in Skyrim.
> 
> The only solution is to not have collidable names.

NiNode* hdt::findNode(NiNode* obj, const BSFixedString& name)
bone name as BSFixedString, should be correct cased. There's some error lies somewhere.

**Comment by DaymareOn** [comment]
It's based on: virtual NiAVObject *	GetObjectByName(const char ** name);
That one is implemented in Skyrim and the error lies in it. Or do I miss something?
