### ISSUE TITLE
[BUG] incompatible with Skyrim AE GOG 1.6.1179

### ISSUE THREAD

**Issue by orthanner** [DaymareOn/hdtSMP64#140]
**Describe the bug**
No library is installed for Skyrim AE GOG 1.6.1179

**To Reproduce**
1. Download FSMP 2.2.1 from Nexus
2. Install the mod
3. No library version will be available to choose and therefore none will be installed.
4. Archive does not contain the library for 1179 build

**Expected behavior**
Mod install and works correctly.

**Desktop:**
 - OS: Windows 11

** FSMP**
- Installed version: 2.2.1
- CUDA: No_CUDA
- AVX: AVX2

**SKSE**
- installed version 2.2.6

**Skyrim**
- 1.6.1179

**Comment by snottyone** [comment]
get the test version for GOG 1197 on the FSMP discord here https://discord.gg/J7HKKnTv

**Comment by orthanner** [comment]
Didn't work
