### ISSUE TITLE
[BUG] FSMP Version 2.3.0 for AE 1.6.1179 Incompatible with 1.6.1179

### ISSUE THREAD

**Issue by JustONOFF** [DaymareOn/hdtSMP64#142]
**Describe the bug**
I downladed the new version of FSMP uploaded today on Nexusmods and installed the version for Skyrim AE 1.6.1179. But after starting the game I get an error meesage from SKSE, saying hdtSMP64.dll is incompatible with the newest version of Skyrim. I tried to install several versions of FSMP, all spat out the same error message.

**To Reproduce**
1. Install FSMP for 1.6.1179
2. Activate mod on MO2
3. Start the game with the SKSE launcher

**Expected behavior**
Game start normally as expected, no error message about the plugin

**Screenshots and videos**
If applicable, add screenshots or videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11

** FSMP**
- 2.3.0
- CUDA: No_CUDA and CUDA version
- AVX: AVX, AVX2

**SKSE**
- 2.2.6

**Skyrim**
- 1.6.1179

**Required files**

**Additional context**

**Comment by VF27LUCIFER** [comment]
update SKSE, you are using the wrong version
![Screenshot_2](https://github.com/DaymareOn/hdtSMP64/assets/169086922/0369b1cf-19a4-49c5-ace8-4b4ab9f2f151)

**Comment by IvanA2P** [comment]
Same for me i needed to go back to test build 11

**Comment by orthanner** [comment]
Same here, the latest version is reported incompatible

**Comment by DaymareOn** [comment]
Working on it.

**Comment by DaymareOn** [comment]
Reproduced

**Comment by DaymareOn** [comment]
Fixed

**Comment by DaymareOn** [comment]
Fixed in FSMP 2.3.1, released on the nexus.
