### ISSUE TITLE
[BUG] Game refuses to load and crashes with FSMP saying its for an incorrect version

### ISSUE THREAD

**Issue by T3CHNERD** [DaymareOn/hdtSMP64#146]
**Describe the bug**

**To Reproduce**
1. Install FSMP using MO2 with no overwrites (GOG Version of Skyrim is selected)
2. Launch SKSE in MO2
3. Get error
4. Boot game anyways, it crashes when hitting new game

**Expected behavior**
Game should load without error

**Screenshots and videos**
![image](https://github.com/DaymareOn/hdtSMP64/assets/26820815/83329a4b-2827-4d93-91c3-a76814575b73)

**Desktop (please complete the following information):**
 - OS: Windows 11

** FSMP**
- Installed version 2.5.0
(This also occurs using 2.3.1)
- CUDA: No CUDA (Using an AMD GPU)
- AVX: No AVX, AVX & AVX2

**SKSE**
- installed version 2.2.6

**Skyrim**
- Installed version number 1.6.1179

**Required files**
- Join your configs.xml

[configs.txt](https://github.com/user-attachments/files/15812913/configs.txt)
(The attched file is just a renamed xml)

- Join your hdtSMP64.log

hdtSMP64 200500
SEH exception caught while loading FSMP plugin into SKSE.
This exception occurs when a system process, application, or file fails to open, or your system lacks some necessary redistributable packages like Visual C++ extensions.						It can be caused by Damaged or Corrupt system files, Missing files in the registry, Improper configuration of system files, Conflict with third-party programs.						Please see https://www.elevenforum.com/t/0xe06d7363-error-which-fix-to-use.8382/post-201372. SEH exception code: e06d7363
A fatal exception has occurred thrown while reading FSMP's configs.xml

(The above are the only lines in hdtSMP64.log)

**Comment by DaymareOn** [comment]
There is a conflict while reading your configs.xml file.
First, reinstall without the MCM, and check that it solves your bug.
Second, (re-)check that you have all the requirements for the MCM.
If you then still have that problem with the MCM installed, contact us on the discord server to debug the problem.
