### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by HEX460N** [DaymareOn/hdtSMP64#151]
the game crashes when starting any save, even when playing a new game

https://github.com/user-attachments/assets/a0236365-807a-4afd-a4c8-38665b59bb82

 - OS: Windows 10

** FSMP**
- Installed version - 2.5.0
- CUDA: No_CUDA
- AVX: No_AVX

**SKSE**
- installed version - 2.2.6 (game version 1.6.1170)

**Skyrim**
- Installed version number - 1.6.1170 (latest version from steam on 25.08.2024)

**Required files**
[hdtSMP64.txt](https://github.com/user-attachments/files/16738001/hdtSMP64.txt)
[configs.txt](https://github.com/user-attachments/files/16738005/configs.txt)

**Additional context**
I installed only what is necessary for FSMP to work - Faster HDT-SMP, I tried to choose no AVX, AVX 1, 2, 512, CUDA, no CUDA, with any option the game crashes, before enabling Faster HDT-SMP the game does not crash

**Comment by snottyone** [comment]
install the crashlogger from [here](https://www.nexusmods.com/skyrimspecialedition/mods/59818) and post a crashlog here please. (logs are here c:\Users\<you>\Documents\My Games\Skyrim Special Edition\SKSE\)
easier if you can join [our discord](https://discord.gg/3tFTh4n8)

**Comment by HEX460N** [comment]
[crash-2024-08-24-20-14-47.log](https://github.com/user-attachments/files/16739268/crash-2024-08-24-20-14-47.log)
[crash-2024-08-24-20-15-27.log](https://github.com/user-attachments/files/16739269/crash-2024-08-24-20-15-27.log)
[crash-2024-08-24-20-16-08.log](https://github.com/user-attachments/files/16739270/crash-2024-08-24-20-16-08.log)
[crash-2024-08-24-20-27-23.log](https://github.com/user-attachments/files/16739271/crash-2024-08-24-20-27-23.log)
[crash-2024-08-24-20-30-17.log](https://github.com/user-attachments/files/16739272/crash-2024-08-24-20-30-17.log)
[CrashLogger.log](https://github.com/user-attachments/files/16739273/CrashLogger.log)
[hdtSMP64.log](https://github.com/user-attachments/files/16739274/hdtSMP64.log)
[JContainers64.log](https://github.com/user-attachments/files/16739275/JContainers64.log)
[PapyrusUtilDev.log](https://github.com/user-attachments/files/16739276/PapyrusUtilDev.log)
[skee64.log](https://github.com/user-attachments/files/16739277/skee64.log)
[skse64.log](https://github.com/user-attachments/files/16739278/skse64.log)
[skse64_loader.log](https://github.com/user-attachments/files/16739279/skse64_loader.log)
[crash-2024-08-24-19-36-20.log](https://github.com/user-attachments/files/16739280/crash-2024-08-24-19-36-20.log)
[crash-2024-08-24-19-53-11.log](https://github.com/user-attachments/files/16739282/crash-2024-08-24-19-53-11.log)
[crash-2024-08-24-19-54-02.log](https://github.com/user-attachments/files/16739283/crash-2024-08-24-19-54-02.log)
[crash-2024-08-24-19-59-50.log](https://github.com/user-attachments/files/16739284/crash-2024-08-24-19-59-50.log)
[crash-2024-08-24-20-01-03.log](https://github.com/user-attachments/files/16739285/crash-2024-08-24-20-01-03.log)
[crash-2024-08-24-20-04-30.log](https://github.com/user-attachments/files/16739286/crash-2024-08-24-20-04-30.log)

**Comment by snottyone** [comment]
consoleutil NG instead of consoleutil, problem solved on discord
