### ISSUE TITLE
Cloak clips through character when character back to wind

### ISSUE THREAD

**Issue by alandtse** [DaymareOn/hdtSMP64#37]
With #34, this is noticeable. This may be an xml issue or something we can fix by just importing the full skeleton of the actor for collisions.

Likely related to #36

**Comment by isshininu** [comment]
testing on an armor mod that have collision body and clipping very small or absent. actually, windStrength=2.0 + SkyrimStormSnow weather might be an extremal condition to test this, and with increasing windStrenght clipping only goes worse

**Comment by alandtse** [comment]
Closing this since we'll likely rely on xml authors to fix this constraint.
