### ISSUE TITLE
Provide FSMP for GOG version 1.6.659

### ISSUE THREAD

**Issue by DaymareOn** [DaymareOn/hdtSMP64#53]
**Is your feature request related to a problem? Please describe.**
FSMP doesn't work on the GOG version.

**Describe the solution you'd like**
FSMP to work with Skyrim 1.6.659, provided by GOG.

**Describe alternatives you've considered**
Not providing a FSMP version for GOG.

**Additional context**
None.

**Comment by lufusol** [comment]
https://onedrive.live.com/?authkey=!ANomgYjyTf6bVuY&cid=064A50265CFFC378&id=64A50265CFFC378!116

**Comment by Slider-Whistle** [comment]
I don't really trust the GOG-compatible .dll that's been flying around, would be much more comfortable with a build compiled and endorsed by yourself (I would do it, but I don't currently have a Windows installation...).
If you ever find the time, would you be kind enough to release one?

**Comment by RubenKelevra** [comment]
Would be great to have this version just in the list of selectable versions on the installer.

**Comment by DaymareOn** [comment]
> I don't really trust the GOG-compatible .dll that's been flying around, would be much more comfortable with a build compiled and endorsed by yourself (I would do it, but I don't currently have a Windows installation...). If you ever find the time, would you be kind enough to release one?

I already provided it in the fomod for quite a time. Enjoy :)
The one I don't provide is the Epic version.
