### ISSUE TITLE
CTD with hdt-smp hairs on NPCs

### ISSUE THREAD

**Issue by antpillager** [DaymareOn/hdtSMP64#69]
AE 1.6.640
SKSE 2.2.2

Faster HDT-SMP 1.49 AVX2
HDT-SMP Racemenu Hairs and Wigs 1.21

Had no problems with using HDT-SMP hairs on my character, but the game crashes when I try to apply preset with HDT-SMP hairs to NPC.

Have fixed it by changing this condition
https://github.com/DaymareOn/hdtSMP64/blob/3a69427fd2b78249fffe2818802fd8422f12199f/hdtSMP64/Hooks.cpp#L68

to
`if ((a_skeleton->m_owner && a_skeleton->m_owner->formID == 0x14) || ActorManager::instance()->m_skinNPCFaceParts)`

**Comment by alandtse** [comment]
Thanks. Please submit a PR.

**Comment by DaymareOn** [comment]
Hey antpillager, thank you :)

Could you contact me on discord or nexus please? Or give me a way to DM you, I haven't found a way to do this.

**Comment by antpillager** [comment]
Updated to latest version and eveything works without issues. Closing this. @DaymareOn contacted to you on nexus
