### ISSUE TITLE
Using Skyrim AE version 1.6.353, neither Updates 1.49.2 or 1.49.3 work for me.

### ISSUE THREAD

**Issue by Painbringer07** [DaymareOn/hdtSMP64#77]
**Describe the bug**

Upon installing 1.49.2 or 1.49.3, SMP hairs disappear, SMP outfits and NPCs wearing them also vanish (floating names and voices from the abyss).  Installed AVX2, No_Cuda each time.   Go back to version 1.49 and everything works again (same settings). Oh and I did make sure to install FSMPV Schema.  I have not tried 1.49.1 yet (perhaps I will later).  

My Hardware is MSI 1660 Ti and Ryzen 5 5600X (Skyrim is on a M.2)

Anyway, I'm not to upset about this because 1.49 works pretty well for me (fairly good FPS),
just wanted to let you know.

Thanks for the hard work on this mod.

**Comment by DaymareOn** [comment]
Thank you, would you join on Discord to help test to find the root cause of the bug?

**Comment by DaymareOn** [comment]
1.6.353 isn't supported anymore.
