### ISSUE TITLE
FSMP causes followers to fade away and become invisible

### ISSUE THREAD

**Issue by pumkinhead456** [DaymareOn/hdtSMP64#82]
**Describe the bug**
Hello, so I installed FSMP(Faster HDT-SMP) because I wanted hair physics for AE 1.6.640 and HDT-SMP wasn't available for that version, I also installed an Ada Wong mod to have her as a follower in the game, I go to the location to recruit her(Markath, Temple of Dibella) and then when I take her outside, she just fades away and becomes invisible, I can still interact with her and talk to her and she works normally, but she is invisible, weirdly enough she only goes invisible when I am close to her, when I run a little far from her, she isn't invisible, but once she gets close, gone. This only happens to her and only when FSMP is enabled, any help would be appreciated.
Edit: it seems that this is happening for more of my followers, it's very random as some do work and others just fade away.

**To Reproduce**
1. Ask follower to go outside
2. Go outside
3. Watch follower 

**Expected behavior**
The follower shouldn't fade away.

**Screenshots and videos**
If applicable, add screenshots or videos to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11

** FSMP**
- Installed version: 1.49.3
- CUDA: No CUDA 
- AVX: AVX512?

**Required files**
- Join your configs.xml
[configs.txt](https://github.com/DaymareOn/hdtSMP64/files/10614007/configs.txt)

- Join your hdtSMP64.log
[hdtSMP64.log](https://github.com/DaymareOn/hdtSMP64/files/10614024/hdtSMP64.log)

**Additional context**
Only happens outside (interiors she is visible)

**Comment by Donglin216** [comment]
Same thing for me, the follower will go invisible sometimes and reappear randomly. I think it has something to do with our body mods, I use BHUNP.

**Comment by DaymareOn** [comment]
Should be solved in 1.50.4-rc1.
Please test and report.
Please test with the AVX version first.

**Comment by Donglin216** [comment]
> Should be solved in 1.50.4-rc1. Please test and report. Please test with the AVX version first.

I've since changed to CBBE 3BA, but I've used AVX2 and i'm no longer getting the fading followers issue
