### ISSUE TITLE
After initial load, xml file not being re-read for male bodies.

### ISSUE THREAD

**Issue by sm644** [DaymareOn/hdtSMP64#84]
I am working on collisions without added collision bodies. Pointing femalebody.nif to an xml that declares a triangle shape for Baseshape gives good collision for a wig or cloak without any proxy collision bodies. The nif shapes are declared as internal, rather than private.

Now the issue is that the same procedure for malebody.nif does not work as well. Loading into the game, collision is good, but entering racemenu or using SMP reset causes a complete lack of collision from then on.
It would appear that something in the game engine is preventing the xml file being used in the case of males. The SMP List command shows the male player skeleton as 'inactive, not in scene' at the beginning of the list and as active at the end of the list.
Just for males; females work normally.

**Comment by sm644** [comment]
I have found that the problem is not confined to bodies. I would seem that it is because the male body consists of one shape and the female body has extra shapes.
A physics item containing only one shape will not have collision after an 'smp reset'. It will work again when re-equipped, which I could not do with bodies. 'Smp detail' shows that the collision message is not re-found after 'smp reset'.

**Comment by DaymareOn** [comment]
@sm644 , would you have a ready to use mod to reproduce the pb?

**Comment by sm644** [comment]
Thank you. I sort of confirmed the problem with a Fuse00 Raven mask. I removed the proxy collision mesh, so it was then one single TriShape. Entering showracemenu then stopped collision. smp reset also stops collision until the item is re-equipped.
By the way, I am using the actual femalebody nif for collision. My (smartco) wigs work fine without proxy collision because they are each more than one constituent shape.

**Comment by DaymareOn** [comment]
Oh, you're smartco :) ? Hey smartco :) !

Ok, so,
- this mod: https://www.nexusmods.com/skyrimspecialedition/mods/87655,
- open the male mask nif with nifskope,
- remove the _Fuse00_Raven_Chest_Col BSTriShape,
- in the game, 'smp reset',
Problem proofs:
-  skeleton is seen as inactive, not in scene
- no collision auto-created for the body concerning this mask.

Have I well understood how to reproduce the problem?

**Comment by DaymareOn** [comment]
I think the player appearing 2 times may be related to the 1st person and 3rd person views player bodies.
I'm working on this in parallel.

Found how to modify the nifs in nifskope, added the xml.
Still have to define what I put inside.

**Comment by DaymareOn** [comment]
Thank you. A little pause right now.
I'll continue later, possibly this evening.

**Comment by DaymareOn** [comment]
Reproduced

**Comment by DaymareOn** [comment]
Hey sm644, could you please test this dll? [hdtSMP64.zip](https://github.com/DaymareOn/hdtSMP64/files/11123846/hdtSMP64.zip)
If it doesn't solve your problem, please report the hdtSMP64.log.
It will be very verbose, so in this case please just reproduce 
and leave before providing it.

**Comment by sm644** [comment]
Hi Day,

That has fixed it.
Immediate CTD the first attempt; either coincidence or cache clearing?
Second go, it worked and cured the problem. A lot of delay, because of the log verbosity, I suppose.

You know I am the curious type though. Are you going to tell me what you found?  :-)

smartco.

**Comment by DaymareOn** [comment]
Yes :)
I need to document well what happens...
Will put it in next message, might be long.

CTD worries me though. You tried on exactly the same save?

**Comment by sm644** [comment]
Yes, just the continue game save. I will keep this test dll for awhile and see if it CTDs again.

**Comment by DaymareOn** [comment]
When a smp reset happens, we can't go through the ArmorAttachEvent processing: no event is sent by the skyrim executable.
So for each known skeleton, and each of its known armors meshes, we apply the related xml file.

Each armor has a record of each xml file applies, the names of the meshes of the armor in the xml file / nif, and for each mesh name the name of the NiAVObject attached through the ArmorAttachEvent hook processing.
We can then apply the related xml file to this NiAVObject that we find back through its name.

But!
The skyrim executable changes later the name of the NiAVObject passed as attachedNode through the ArmorAttachEvent hook.
So, when trying to find the recorded name in the existing objects, we don't find it anymore.

The proposed solution is to save the original name, detect on a following event when that name has changed, and save the new name too.

4 days to diagnose and solve this...!

**Comment by sm644** [comment]
It seemed to work ok with nifs that had more than one constituent shape. I'm not sure that your explanation covers that aspect.

On a less general note, I can't get that dll to run again on my system. It crashed first time, second attempt then ran slowly to allow proof of the Raven mask enduring an smp reset. Now it CTDs, even when older saves are loaded. A reboot hasn't helped, but going back to my old dll has returned me to normal.

**Comment by DaymareOn** [comment]
Finished refactoring and beautifying my code.
Will re-test and release another test version in the next days.

**Comment by sm644** [comment]
Merci bien.

**Comment by DaymareOn** [comment]
Hey sm644, could you please test this version [hdtSMP64.zip](https://github.com/DaymareOn/hdtSMP64/files/11137269/hdtSMP64.zip) ?
If you don't report any problem, it's final.
Thank you for the remark on ctds, I had to test in solitude rather than only on one skeleton to have it happen to me.

**Comment by sm644** [comment]
Hi Day, I have reopened this as an aide memoire, because it is happening again, sort of. I never use body slot armours with only one included shape, but I have just had occasion to. An smp reset stops collision on the armour and re-equipping fixes it. Adding another shape to the nif also fixes it. When it is working, smp detail reports the collision shape as BODY, though my xml declares it as Body.
I am on the latest release of FSMP.

Smartco.

**Comment by DaymareOn** [comment]
Thank you smartco, working on it :)

**Comment by DaymareOn** [comment]
Could you test this?

[hdtSMP64-issue84-test.zip](https://github.com/user-attachments/files/29612903/hdtSMP64-issue84-test.zip)

**Comment by sm644** [comment]
Sorry for the delay. That test makes it function correctly. However, now it details every shape I have declared in my xml, rather than just the shape that is actually present. Also Body is still being changed to all caps. The shape Pack, though not present, is also being capitalised. Other shapes in the xml are being written normally.

**Comment by sm644** [comment]
You can see my method and my general collision xml in my mod here.
https://www.patreon.com/Smartco/posts/aela-162476150
although it doesn't have the problematic one shape armour.

**Comment by DaymareOn** [comment]
Ok, could you test this one please?
[hdtSMP64-issue84-test-v3.zip](https://github.com/user-attachments/files/29631391/hdtSMP64-issue84-test-v3.zip)

Btw, nice replacers!

**Comment by sm644** [comment]
Thanks. I have just added Jordis which has the armour in question. I have added a shape, so the problem is gone.

Back to the single shape version though, game load shows no active physics system for the armour. Re-equipping makes it work and it details the shape Body, with correct letter case, Smp reset puts it back to no active physics system. Though hair always moves, just doesn't collide.
