### ISSUE TITLE
Game crashes 

### ISSUE THREAD

**Issue by Kirill1R** [DaymareOn/hdtSMP64#88]
**Describe the bug**
Game crashes  when i use any outfit with smp physic

**To Reproduce**
1. Turn on FSMP
2. Launch game
3. i dress any outfit with smp physic
4. Game crashes

**Expected behavior**
Play with SMP physic
**Screenshots and videos**
Game crashes

**Desktop (please complete the following information):**
 - OS: [Windows 7, x64]

** FSMP**
- 1.49.0 (i also try 1.49.3 and i have same problem)
- CUDA: No_CUDA
- AVX: No_AVX

**SKSE**
- 2.0.20

**Skyrim**
- 1.5.97

**Required files**
- Join your configs.xml
[configs.zip](https://github.com/DaymareOn/hdtSMP64/files/10927899/configs.zip)

- Join your hdtSMP64.log
[hdtSMP64.log](https://github.com/DaymareOn/hdtSMP64/files/10927900/hdtSMP64.log)

**Additional context**
- 
[crash-2023-03-09-04-46-19.log](https://github.com/DaymareOn/hdtSMP64/files/10927891/crash-2023-03-09-04-46-19.log)

**Comment by alandtse** [comment]
Update to the latest. No one is going to support a version that old.

**Comment by Kirill1R** [comment]
> Update to the latest. No one is going to support a version that old.

What i need to update? skyrim,skse,windows,?

**Comment by alandtse** [comment]
FSMP.

**Comment by Kirill1R** [comment]
Did not help, game crashes

**Comment by alandtse** [comment]
Please update the ticket with the versions you're using and make sure you're using a debug version. You will need to also install a [crashlogger that can read the PDB](https://www.nexusmods.com/skyrimspecialedition/mods/59818/?tab=description) that is included with the debug version. .Net Framework cannot. The PDB is needed for us to determine where in the dll it is crashing.

**Comment by Spookghost22** [comment]
Got the same issue. Still haven't been able to find a solution. Which sucks since a lot of mods require FSMP. I will try to find a fix and will post the solution here if I find one

**Comment by Spookghost22** [comment]
> Got the same issue. Still haven't been able to find a solution. Which sucks since a lot of mods require FSMP. I will try to find a fix and will post the solution here if I find one

Alright I fixed it. Apparently it crashed everytime I equiped an armor from Immersive armors which hasn't been updated since 2016. I simply installed a CBBE conversion and now my game doesn't crash anymore.

**Comment by DaymareOn** [comment]
> > Got the same issue. Still haven't been able to find a solution. Which sucks since a lot of mods require FSMP. I will try to find a fix and will post the solution here if I find one
> 
> Alright I fixed it. Apparently it crashed everytime I equiped an armor from Immersive armors which hasn't been updated since 2016. I simply installed a CBBE conversion and now my game doesn't crash anymore.

Could you please tell me the precise armor so that I test if I can reproduce this CTD?

**Comment by Spookghost22** [comment]
> > > Got the same issue. Still haven't been able to find a solution. Which sucks since a lot of mods require FSMP. I will try to find a fix and will post the solution here if I find one
> > 
> > 
> > Alright I fixed it. Apparently it crashed everytime I equiped an armor from Immersive armors which hasn't been updated since 2016. I simply installed a CBBE conversion and now my game doesn't crash anymore.
> 
> Could you please tell me the precise armor so that I test if I can reproduce this CTD?

The exact armor I used was the Spellbinder Runic armor for the body.

**Comment by DaymareOn** [comment]
Thank you, installing it on a 1.6.640 test install doesn't make me CTD.
