### ISSUE TITLE
Crash with Witcher Horses Expansion

### ISSUE THREAD

**Issue by Pop000100** [DaymareOn/hdtSMP64#98]
**Describe the bug**
The witcher horse expansion CTDs if this mod is enabled with xpsme lite or full.

**To Reproduce**
Go to the storm altar which is next to [Shrine of Akatosh in falkreath hold](https://en.uesp.net/wiki/Skyrim:Shrines#Twilight_Valley)

**Expected behavior**
The game continues to run as it does without HDT-SMP.

**Desktop (please complete the following information):**
Windows 10

** FSMP**
- Installed version
- CUDA: No_CUDA
- AVX: AVX2

**SKSE**
- installed version
2.2.3

**Skyrim**
1.6.640

**Required files**
[hdtSMP64.log](https://github.com/DaymareOn/hdtSMP64/files/11154329/hdtSMP64.log)
[crash-2023-04-05-01-18-37.log](https://github.com/DaymareOn/hdtSMP64/files/11154330/crash-2023-04-05-01-18-37.log)
[configs.txt](https://github.com/DaymareOn/hdtSMP64/files/11154332/configs.txt)

**Comment by Pop000100** [comment]
I would like to mention the debug version of 1.50.4 doesn't load 

loading plugin "HDT-SMP Force Fields"
registering plugin listener for SKSE at 35 of 117
plugin HDT-SMP Force Fields.dll (00000001 HDT-SMP Force Fields 00090000) loaded correctly (handle 35)
loading plugin "hdtSMP64"
plugin hdtSMP64.dll (00000001 hdtSMP64 00019A2C) disabled, fatal error occurred while loading plugin 0 (handle 36)

**Comment by Pop000100** [comment]
This crash was fixed on the mods side(still probably should fail gracefully if it meets a similar issue)
`I found the cause. Among the nodes attached to Thunder's horn, EnbParticleLight02 was the problem. Just delete EnbParticleLight02 from the node and the crash won't happen.I'm glad it's a problem that can be easily solved without changing the skeleton. `

**Comment by alandtse** [comment]
Thanks. Since it's a particle light node, it's probably a non standard node so may be missing some data expected for physics.
